[package]
name = "quic_over_socket_api"
version = "0.1.0"
edition = "2021"

[lib]
name = "quic_over_socket_api"
crate-type = ["cdylib", "staticlib"]

[workspace]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.153"
quiche = "0.20.0"
slice = "0.0.4"
